services:
  _defaults:
    tags: ['huh.contao_twig_templates.framework']
    autowire: true

  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\Bootstrap3Framework: ~
  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\Bootstrap4Framework: ~