services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  huh.twig.event_listener.hook_listener:
    class: HeimrichHannot\TwigTemplatesBundle\EventListener\HookListener
    public: true
    autowire: true

  HeimrichHannot\TwigTemplatesBundle\EventListener\GetAttributesFromDcaListener:
    public: true
    autowire: true

  HeimrichHannot\TwigTemplatesBundle\EventListener\BeforeRenderTwigTemplateEventListener:
    public: true
    autowire: true
    tags:
      - { name: kernel.event_listener, event: huh.twig_support.before_render_twig_template, method: '__invoke' }
