services:
  _defaults:
    autowire: true

  HeimrichHannot\TwigTemplatesBundle\:
    resource: "../../{DataContainer,EventListener}/*"
    public: true

  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\:
    resource: "../../FrontendFramework/*"
    tags: ['huh.contao_twig_templates.framework']

  HeimrichHannot\TwigTemplatesBundle\EventListener\RenderListener:
    tags:
      - { name: kernel.event_listener, event: huh.twig_support.before_parse_twig_template, method: "onBeforeParseTwigTemplateEvent" }
      - { name: kernel.event_listener, event: huh.twig_support.before_render_twig_template, method: "onBeforeRenderTwigTemplateEvent" }

  HeimrichHannot\TwigTemplatesBundle\Twig\TwigTemplatesExtension:
    tags:
      - { name: twig.extension }

  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\FrontendFrameworkCollection:
    public: true