services:
  huh.twig.template.factory:
    class: HeimrichHannot\TwigTemplatesBundle\Twig\TemplateFactory
    public: true
    autowire: true
  huh.twig.template.twig_extension:
    class: HeimrichHannot\TwigTemplatesBundle\Twig\TwigTemplatesExtension
    public: false
    tags:
      - {name: twig.extension}
  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\FrontendFrameworkCollection:
    public: true
    autowire: true