services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\TwigTemplatesBundle\:
    resource: "../../{DataContainer,EventListener,EventSubscriber}/*"

  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\Concrete\:
    resource: "../../FrontendFramework/Concrete/*"
    tags: ['huh.contao_twig_templates.framework']

  HeimrichHannot\TwigTemplatesBundle\Twig\TwigTemplatesExtension:
    tags:
      - { name: twig.extension }

  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\FrontendFrameworkCollection:
    public: true