services:
  _defaults:
    autowire: true

  HeimrichHannot\TwigTemplatesBundle\:
    resource: "../../{DataContainer}/*"
    public: true

  HeimrichHannot\TwigTemplatesBundle\EventListener\RenderListener:
    tags:
      - { name: kernel.event_listener, event: huh.twig_support.before_parse_twig_template, method: "onBeforeParseTwigTemplateEvent" }
      - { name: kernel.event_listener, event: huh.twig_support.before_render_twig_template, method: "onBeforeRenderTwigTemplateEvent" }

  huh.twig.template.factory:
    class: HeimrichHannot\TwigTemplatesBundle\Twig\TemplateFactory
    public: true
  HeimrichHannot\TwigTemplatesBundle\Twig\TemplateFactory: '@huh.twig.template.factory'

  huh.twig.template.twig_extension:
    class: HeimrichHannot\TwigTemplatesBundle\Twig\TwigTemplatesExtension
    public: false
    tags:
      - { name: twig.extension }

  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\FrontendFrameworkCollection:
    public: true
