services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\TwigTemplatesBundle\:
    resource: "../../{DataContainer,EventListener}/*"

  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\Concrete\:
    resource: "../../FrontendFramework/Concrete/*"
    tags: ['huh.contao_twig_templates.framework']

  HeimrichHannot\TwigTemplatesBundle\EventListener\RenderListener:
    tags:
      - { name: kernel.event_listener, event: huh.twig_support.before_parse_twig_template, method: "onBeforeParseTwigTemplateEvent", priority: 100 }
      - { name: kernel.event_listener, event: huh.twig_support.before_render_twig_template, method: "onBeforeRenderTwigTemplateEvent", priority: 100 }

  HeimrichHannot\TwigTemplatesBundle\Twig\TwigTemplatesExtension:
    tags:
      - { name: twig.extension }

  HeimrichHannot\TwigTemplatesBundle\FrontendFramework\FrontendFrameworkCollection:
    public: true